# 你的 GitHub username
owner: ssangyongsports

# 你的 GitHub repo name
repo: upptime

# 加入要監控的網站名稱與 URL
sites:
  - name: AnnKuoQ Blog
    url: https://annkuoq.github.io/blog/

# 移除 cname，因為我沒有自己的 domain，所以改用 baseUrl，輸入 repo 名稱
status-website:
    #cname: demo.upptime.js.org (移除)
    baseUrl: /upptime 

# 自訂狀態頁面的 navbar 名稱與連結
navbar:
    - title: Status
      href: /upptime
